//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssignmentWebASP.NET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int id { get; set; }
        public decimal amount { get; set; }
        public int productId { get; set; }
        public int orderId { get; set; }
        public int imageId { get; set; }
        public int sizeId { get; set; }
        public int materialId { get; set; }
    
        public virtual Image Image { get; set; }
        public virtual Material Material { get; set; }
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
        public virtual Size Size { get; set; }
    }
}
